
// Open MoneySpinner Suite v1
// An open source business management software system written in Java and MySQL
// Recommended IDE is NetBeans IDE 7.0.1
// Support Web Site: http://www.milliscript.com
//
// Copyright (C) 2014, Abiodun Aremu, Ibadan/NIGERIA.
// Open MoneySpinner Suite is distributed under the terms of the Apache License version 2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Login.java
 *
 * Created on Jan 25, 2011, 12:03:38 AM
 */

package openmoneyspinnersuite;

/**
 *
 * @author Abiodun Aremu
 */
import javax.swing.*;

final  class Login extends javax.swing.JFrame
{
    Systems systems=new Systems();
    Thread tread;Thread accountTitleThread;
    /** Creates new form Login */
     Login()
    {   
        Connect.createMSSQLConnection();
        java.sql.PreparedStatement statement=Connect.createStatement("set global sql_mode=ANSI"); 
        Connect.executeUpdateStatement(statement);
        Connect.alert="N";
        Connect.closeConnection();
        this.setTitle("::. Milliscript MoneySpinner Suite Server 1.5.1");
        if(OpenMSApp.ApplicationLogon.equalsIgnoreCase("First"))
        {
            Splash ne=new Splash();
            ne.display();
            ne.setVisible(true);
            //loadSplashScreen();
            ne.dispose();
            System.out.println("Splash disposed.");
        }
        else
        {
            System.out.println("Splash Not Loaded.");
        }
        initComponents();
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(openmoneyspinnersuite.OpenMSApp.class).getContext().getResourceMap(Login.class);
        String filePath=resourceMap.getResourcesDir()+"MiliscriptDMS_logo.png";
        java.net.URL url = resourceMap.getClassLoader().getResource(filePath);
        this.setIconImage(getToolkit().getImage (url));
        System.out.println(url);
//        java.awt.Image m=resourceMap.getImageIcon("MiliscriptDMS_logo.png").getImage();
//        this.setIconImage(resourceMap.getImageIcon("loginButton.icon").getImage());
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setDefaultLookAndFeelDecorated(true);
        this.getRootPane().setDefaultButton(loginButton);
        OpenMSApp.ApplicationLogon="More";
        Configuration.setConfigurations();
        String computerNetAddress="";
        resetCompany();
        accountTitleThread=new Thread(new Runnable() {
            public void run() {
                while(true)setProcessingTitle(accountTitleThread);
            }
        });
        accountTitleThread.start();
        /**
         *
         * Code To Enforce Single Use of Software Per System
         * "user-f8e773e194""abbeytec-3ad1e3""BYL-PC""MrOnum-PC"
         **/
        if(!OpenMSApp.appType.equals("AX, Server, Trial"))
        try
        {
            String try1=java.net.Inet4Address.getLocalHost().getHostAddress();
            computerNetAddress=java.net.InetAddress.getLocalHost().getHostName();
           
            if(computerNetAddress.equals("Abiodun-PC")==false)
            {
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame()," UNAUTHORIZED MACHINE ! \n ERROR CODE: 001001 ","LAUNCH ERROR",JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
        catch(Exception e)
        {
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCompanyComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jIPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(openmoneyspinnersuite.OpenMSApp.class).getContext().getResourceMap(Login.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        usernameLabel.setFont(resourceMap.getFont("usernameLabel.font")); // NOI18N
        usernameLabel.setText(resourceMap.getString("usernameLabel.text")); // NOI18N
        usernameLabel.setName("usernameLabel"); // NOI18N

        passwordLabel.setFont(resourceMap.getFont("passwordLabel.font")); // NOI18N
        passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
        passwordLabel.setName("passwordLabel"); // NOI18N

        usernameTextField.setFont(resourceMap.getFont("usernameTextField.font")); // NOI18N
        usernameTextField.setText(resourceMap.getString("usernameTextField.text")); // NOI18N
        usernameTextField.setName("usernameTextField"); // NOI18N
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        usernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameTextFieldKeyTyped(evt);
            }
        });

        jPasswordField.setFont(resourceMap.getFont("jPasswordField.font")); // NOI18N
        jPasswordField.setText(resourceMap.getString("jPasswordField.text")); // NOI18N
        jPasswordField.setName("jPasswordField"); // NOI18N
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyTyped(evt);
            }
        });

        loginButton.setFont(resourceMap.getFont("loginButton.font")); // NOI18N
        loginButton.setIcon(resourceMap.getIcon("loginButton.icon")); // NOI18N
        loginButton.setText(resourceMap.getString("loginButton.text")); // NOI18N
        loginButton.setName("loginButton"); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCompanyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCompanyComboBox.setName("jCompanyComboBox"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jIPanel.setBackground(resourceMap.getColor("jIPanel.background")); // NOI18N
        jIPanel.setName("jIPanel"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jIPanelLayout = new javax.swing.GroupLayout(jIPanel);
        jIPanel.setLayout(jIPanelLayout);
        jIPanelLayout.setHorizontalGroup(
            jIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jIPanelLayout.setVerticalGroup(
            jIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loginButton)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(usernameLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jCompanyComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCompanyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jIPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                       
    private void setProcessingTitle(Thread thread)
    {        
        try
        {
            String try1=java.net.Inet4Address.getLocalHost().getHostAddress();
            jLabel3.setText("       IP: "+try1);
            OpenMSApp.curIP=" | IP: "+try1;
            thread.sleep(500);
        }
        catch(Exception e)
        {

        }
    }
    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        if(Connect.connect==null)Connect.createMSSQLConnection();
        String companyAvailable=systems.getValue(OpenMSApp.Database_C, "Select * from company",1);
        
        if(String.valueOf(jCompanyComboBox.getSelectedItem()).trim().equalsIgnoreCase("-- Select --")&&companyAvailable.isEmpty()==false)
        {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"Please select a company ","Execution ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        OpenMSApp.Database_A=String.valueOf(jCompanyComboBox.getSelectedItem()).trim().replace(" ", "_").replace("-", "0");
        String[] args={};
        String password=String.valueOf(jPasswordField.getPassword()).trim();
        String username=usernameTextField.getText().trim();
        String loginComputerAddress="";
        String computerNetAddress="";
        String adminAvailable=systems.getValue(OpenMSApp.Database_A, "Select * from login where cProcess = 'admin' and cStatus='Active'",1);
        try
        {

        computerNetAddress=java.net.InetAddress.getLocalHost().getHostName();
//        String try0=java.net.Inet4Address.getLocalHost().getCanonicalHostName();
        String try1=java.net.Inet4Address.getLocalHost().getHostAddress();
//        String try2=java.net.Inet4Address.getLocalHost().getHostName();
//        String try3=java.net.Inet6Address.getLocalHost().getHostAddress();
//        String try4=java.net.Inet6Address.getLocalHost().getCanonicalHostName();
//        String try5=java.net.Inet6Address.getLocalHost().getHostName();
//        String try6=java.net.InetAddress.getLocalHost().getCanonicalHostName();
//        String try7=java.net.InetAddress.getLocalHost().getHostAddress();
//        String try8=java.net.InetAddress.getLocalHost().getHostName();
//        String try9=java.net.InetSocketAddress.createUnresolved("localhost", 0).toString();
//        String try10;
        System.out.println("This computer address= "+computerNetAddress);
        System.out.println("This computer ip address= "+try1);
        }catch(Exception e)
        { System.out.println("Error occured while retrieving localHostAddress"+e);}
        String computerUserName=System.getProperty("user.name");
        String osName=System.getProperty("os.name");
        System.out.println(computerUserName+" "+osName);
        loginComputerAddress=computerUserName+"@"+computerNetAddress;
        
        Connect.alertRollBack="N";
        if(usernameTextField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"Please Enter Your Username ","Execution ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(String.valueOf(jPasswordField.getPassword()).trim().isEmpty())
        {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"Please Enter Your Password ","Execution ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(usernameTextField.getText().trim().equals("mS")&&password.equals("DMS")&&adminAvailable.isEmpty()==true)
        {
            //setUserParameter(usernameTextField.getText());
            OpenMSApp.EmployeeName="System Setup";
            OpenMSApp.launch(OpenMSApp.class, args);
            this.dispose();
            return;
        }
        else
        {
            String access=systems.getValue(OpenMSApp.Database_A, Connect.procInit+" prnConfirmLogin"+Connect.procInitStart+"'"+username+"' , '"+password+"', '"+loginComputerAddress+"'"+Connect.procInitEnd, "cState");

            String trialState=systems.getValue(OpenMSApp.Database_C, Connect.procInit+" prnConfirmTrial"+Connect.procInitStart+"'"+OpenMSApp.trialCode+"' , '"+loginComputerAddress+"'"+Connect.procInitEnd, "cState");
//CODE TO ENFORCE TRIAL CONTROL
        if(OpenMSApp.appType.equals("AX, Server, Trial"))
        {
            //to popup computer net address
            /*
            try
            {
                computerNetAddress=java.net.InetAddress.getLocalHost().getHostName();
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"computerNetAddress "+computerNetAddress,"Execution ERROR",JOptionPane.ERROR_MESSAGE);
                
            }catch(Exception e){}
            //*/
            if(trialState.equalsIgnoreCase("expired"))
            {
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"SORRY, THE TRIAL PERIOD OF THIS SOFTWARE HAS EXPIRED !","Execution ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(trialState.equalsIgnoreCase("valid"))
            {
                String trialDay=systems.getValue(OpenMSApp.Database_C, Connect.procInit+" prnConfirmTrial"+Connect.procInitStart+"'"+OpenMSApp.trialCode+"' , '"+loginComputerAddress+"'"+Connect.procInitEnd, "iDayLeft");
                OpenMSApp.trialDay=trialDay;
                if(Integer.parseInt(trialDay)<7)
                {
                    JOptionPane.showMessageDialog(JOptionPane.getRootFrame()," THE TRIAL PERIOD OF MILLISCRIPT MONEYSPINNER 1.4.0 \n IS NOW "+trialDay+" DAYS LEFT","ERROR !",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
            if(access.equalsIgnoreCase("Blocked"))
            {
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"             Access Blocked !\n Please see your System Administrator","ERROR !",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(access.equalsIgnoreCase("Active"))
            {
                setUserParameter(usernameTextField.getText());
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"      Welcome ! \n "+OpenMSApp.EmployeeName,"Execution COMPLETE",JOptionPane.INFORMATION_MESSAGE);

                OpenMSApp.launch(OpenMSApp.class, args);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"Invalid Username and Password Combination","Execution ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Connect.closeMainConnection();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTextFieldKeyTyped
        // TODO add your handling code here:
        String value=usernameTextField.getText();
        if(value.length()>9)
        {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"Maximum Number of Character (10) Exceeded ","Execution ERROR",JOptionPane.ERROR_MESSAGE);
            String newValue=String.copyValueOf(value.toCharArray(),0, 9);
            usernameTextField.setText(newValue);
        }

    }//GEN-LAST:event_usernameTextFieldKeyTyped

    private void jPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyTyped
        // TODO add your handling code here:
        String value=String.valueOf(jPasswordField.getPassword());
        if(value.length()>9)
        {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"Maximum Number of Character (10) Exceeded ","Execution ERROR",JOptionPane.ERROR_MESSAGE);
            String newValue="";
            jPasswordField.setText(newValue);
        }
    }//GEN-LAST:event_jPasswordFieldKeyTyped
     void setUserParameter(String userName)
    {
        Systems systems=new Systems();
        OpenMSApp.LoginCode=systems.getValue(OpenMSApp.Database_A, "Select * from login where vusername= '"+userName+"'", "cLoginCode").trim();
        OpenMSApp.EmployeeID=systems.getValue(OpenMSApp.Database_A, "Select * from login where vusername= '"+userName+"'", "cEmployeeID").trim();
        OpenMSApp.EmployeeName=systems.getValue(OpenMSApp.Database_A,"Select * from Employee where cEmployeeID= '"+OpenMSApp.EmployeeID+"'","vFirstName").trim()+" "+
                        systems.getValue(OpenMSApp.Database_A,"Select * from Employee where cEmployeeID= '"+OpenMSApp.EmployeeID+"'","vMiddleName").trim()+" "+
                        systems.getValue(OpenMSApp.Database_A,"Select * from Employee where cEmployeeID= '"+OpenMSApp.EmployeeID+"'","vlastName").trim();
        OpenMSApp.CompanyName=jCompanyComboBox.getSelectedItem().toString();
        OpenMSApp.CompanyAddress=systems.getValue(OpenMSApp.Database_C, "Select vAddress from company where vName='"+OpenMSApp.CompanyName+"'", 1);
        OpenMSApp.CompanyPhone=systems.getValue(OpenMSApp.Database_C, "Select cPhone from company where vName='"+OpenMSApp.CompanyName+"'", 1);
        OpenMSApp.UserName=userName;
        OpenMSApp.userProcess=systems.getValue(OpenMSApp.Database_A, "Select * from login where vusername= '"+userName+"'", "cProcess").trim();
    }
    
     void resetCompany()
    {
        String[] company=systems.getTableDataArray(OpenMSApp.Database_C,"Company",2);
        company[0]="-- Select --";

        jCompanyComboBox.setModel(new DefaultComboBoxModel(company));
    }
    
   void loadSplashScreen()
  {
      tread=new Thread();
     System.out.println("Splash Loaded");
    //Start the thread
      try
      {
        //Display the FormSplash for 10 seconds
        System.out.println("Splash sleeping...");
        tread.sleep(5000);
      }
      catch(InterruptedException e)
      {
      }

  }

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCompanyComboBox;
    private javax.swing.JPanel jIPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}
